openapi: "3.0.0"

info:
  title: "AUDL Game Forecaster"
  description: "API that accepts two AUDL team abbreviations and returns win probabilities."
  version: "1.0"

paths:
  /forecast:
    post:
      description: "Extract elo predictions"

      requestBody:
        description: "Json with fields for home team and away team"
        required: true
        content:
          application/json: {}

      responses:
        '200':
          description: "Returns percentage chance of each team winning as well as predicted margin of victory"
          content:
            application/json: {}
